substitutions:
  name: raphsreef
  friendly_name: raphsreef
packages:
  twinsen68.raphsreef: github://twinsen68/raph/raphsreef_config.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false # or true
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: Y+CW+hILdfh2CwPEafOL59BYD0Y6o2quSiyG2ZKs8Aw=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password