substitutions:
  name: raphsreef
  friendly_name: raphsreef
packages:
  twinsen68.raphsreef: github://twinsen68/Raph/raphsreef_config.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false # or true
  friendly_name: ${friendly_name}
  
api:
  encryption:
    key: EtryKOqGLljX2SSM1CWrA0ys2bLGXc4CrjViG0Hm8GA=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password